version: '3.8'

services:
  kbchatbot:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - VITE_OPENAI_API_KEY=${VITE_OPENAI_API_KEY}
        - VITE_SUPABASE_URL=${VITE_SUPABASE_URL}
        - VITE_SUPABASE_KEY=${VITE_SUPABASE_KEY}
        - VITE_GOOGLE_CLIENT_ID=${VITE_GOOGLE_CLIENT_ID}
        - VITE_GOOGLE_API_KEY=${VITE_GOOGLE_API_KEY}
        - VITE_META_APP_ID=${VITE_META_APP_ID}
        - VITE_EVOLUTION_BASE_URL=${VITE_EVOLUTION_BASE_URL}
        - VITE_EVOLUTION_GLOBAL_API_KEY=${VITE_EVOLUTION_GLOBAL_API_KEY}
    networks:
      - coolify

networks:
  coolify:
    external: true
